title: Syazaril Asyraf # name of the site
author: Syazaril Asyraf # name of site's author
email: wan@syazarilasyraf.com # email of site's author
url: https://syazarilasyraf.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: Hello ğŸ‘‹ I'm Syazaril Asyraf. I build things for the web. # description of the site (multiple lines allowed)

permalink: /:slug.html

header_pages:
 - index.md
 - about.md
 - writing.md
 - notes.md
 - projects.md
#  - contact.md

include:
  - _bookmarks
  - _tools

collections:
  bookmarks:
    output: true
    permalink: /:collection/:title

  tools:
      output: true
      permalink: /tools/:title

footer: '<p><a href="https://github.com/syazarilasyraf/syazarilasyraf.com?tab=readme-ov-file#syazarilasyrafcom">Readme</a> ğŸ± </p>'

# <p>Current Status: <span id="current-status"></span></p>

# settings

style: dark

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag